import { LOCATION_ADMIN } from "./routes";

export const ADMIN_NAV_ITEMS = [
  {
    href: `${LOCATION_ADMIN}?view=location&tab=general`,
    label: "Settings",
    section: "Locations",
    view: "location",
    tab: "general",
  },
  {
    href: `${LOCATION_ADMIN}?view=location&tab=menus`,
    label: "Menus",
    section: "Locations",
    view: "location",
    tab: "menus",
  },
  {
    href: `${LOCATION_ADMIN}?view=location&tab=beverages`,
    label: "Beverage Menus",
    section: "Locations",
    view: "location",
    tab: "beverages",
  },
  {
    href: `${LOCATION_ADMIN}?view=location&tab=rates`,
    label: "Rates",
    section: "Locations",
    view: "location",
    tab: "rates",
  },
  {
    href: `${LOCATION_ADMIN}?view=location&tab=calendar`,
    label: "Calendar",
    section: "Locations",
    view: "location",
    tab: "calendar",
  },
  {
    href: `${LOCATION_ADMIN}?view=location&tab=ordering`,
    label: "Ordering Links",
    section: "Locations",
    view: "location",
    tab: "ordering",
  },
  {
    href: `${LOCATION_ADMIN}?view=location&tab=career`,
    label: "Career Emails",
    section: "Locations",
    view: "location",
    tab: "career",
  },
  {
    href: `${LOCATION_ADMIN}?view=location&tab=map`,
    label: "Map",
    section: "Locations",
    view: "location",
    tab: "map",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=settings`,
    label: "Business Settings",
    section: "Business",
    view: "business",
    tab: "settings",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=fittings`,
    label: "Fittings",
    section: "Business",
    view: "business",
    tab: "fittings",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=junior-golf`,
    label: "Junior Golf",
    section: "Business",
    view: "business",
    tab: "junior-golf",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=franchise-inquiries`,
    label: "Franchise Inquiries",
    section: "Inquiries",
    view: "business",
    tab: "franchise-inquiries",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=career-inquiries`,
    label: "Career Inquiries",
    section: "Inquiries",
    view: "business",
    tab: "career-inquiries",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=lesson-inquiries`,
    label: "Lesson Inquiries",
    section: "Inquiries",
    view: "business",
    tab: "lesson-inquiries",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=league-inquiries`,
    label: "League Inquiries",
    section: "Inquiries",
    view: "business",
    tab: "league-inquiries",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=membership-inquiries`,
    label: "Membership Inquiries",
    section: "Inquiries",
    view: "business",
    tab: "membership-inquiries",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=fitting-inquiries`,
    label: "Fitting Inquiries",
    section: "Inquiries",
    view: "business",
    tab: "fitting-inquiries",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=event-inquiries`,
    label: "Event Inquiries",
    section: "Inquiries",
    view: "business",
    tab: "event-inquiries",
  },
  {
    href: `${LOCATION_ADMIN}?view=business&tab=inquiry-settings`,
    label: "Inquiry Settings",
    section: "Inquiries",
    view: "business",
    tab: "inquiry-settings",
  },
] as const;
